/* Generated by lastchange.py, do not edit.*/

#ifndef GPU_CONFIG_GPU_LISTS_VERSION_H_
#define GPU_CONFIG_GPU_LISTS_VERSION_H_

#define GPU_LISTS_VERSION "d7480ef4e139e138ba4aa5b3be3429adca342848"

#endif  // GPU_CONFIG_GPU_LISTS_VERSION_H_
